services:
  postgres:
    image: 'postgres:16.0'
    container_name: 'planner-userdb'
    environment:
      - 'POSTGRES_DB=taskplanner'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
  rabbitmq:
    image: 'bitnami/rabbitmq:3.12.0'
    container_name: 'planner-rabbitmq'
    restart: 'always'
    environment:
      - 'RABBITMQ_PASSWORD=password'
      - 'RABBITMQ_USERNAME=admin'
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./conf/definitions.json:/etc/rabbitmq/definitions.json:ro