services:
  postgres:
    image: 'postgres:16.0'
    container_name: 'planner-db'
    restart: 'always'
    environment:
      POSTGRES_DB: taskplanner
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: admin
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: 'planner-rabbitmq'
    restart: 'always'
    environment:
      RABBITMQ_PASSWORD: ${RMQ_PASSWORD}
      RABBITMQ_USERNAME: admin
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./conf/definitions.json:/etc/rabbitmq/definitions.json:ro
  rest:
    image: romanv79/taskplanner-userservice:v1.0.5
    container_name: 'rest'
    restart: 'always'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      PUBLIC_HOST: ${PUBLIC_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 8090:8085
    depends_on:
      - postgres
      - rabbitmq
  ui:
    image: romanv79/taskplanner-ui:v1.0.5
    container_name: 'ui'
    restart: 'always'
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8088:8080
    depends_on:
      - rest
  scheduler:
    image: romanv79/taskplanner-scheduler:v1.0.2
    container_name: 'scheduler'
    restart: 'always'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_PASSWORD: ${DB_PASSWORD}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
    depends_on:
      - postgres
      - rabbitmq
      - rest
  mail:
    image: romanv79/taskplanner-mailservice:v1.0.0
    container_name: 'mail'
    restart: 'always'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}