services:
  postgres:
    image: 'postgres:16.0'
    container_name: 'planner-db'
    restart: 'always'
    environment:
      POSTGRES_DB: taskplanner
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: admin
  rabbitmq:
    image: 'bitnami/rabbitmq:3.12.0'
    container_name: 'planner-rabbitmq'
    restart: 'always'
    environment:
      RABBITMQ_PASSWORD: ${RMQ_PASSWORD}
      RABBITMQ_USERNAME: admin
    volumes:
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./conf/definitions.json:/etc/rabbitmq/definitions.json:ro
  rest:
    image: romanv79/taskplanner-userservice
    container_name: 'rest'
    restart: 'always'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      PUBLIC_HOST: ${PUBLIC_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - planner-db
      - planner-rabbitmq
  ui:
    image: romanv79/taskplanner-ui
    container_name: 'ui'
    restart: 'always'
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - 8088:8080
    depends_on:
      - rest
  scheduler:
    image: romanv79/taskplanner-scheduler
    container_name: 'scheduler'
    restart: 'always'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_PASSWORD: ${DB_PASSWORD}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
    depends_on:
      - planner-db
      - planner-rabbitmq
      - rest
  mail:
    image: romanv79/taskplanner-mailservice
    container_name: 'mail'
    restart: 'always'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      MAIL-USERNAME: ${MAIL-USERNAME}
      MAIL-PASSWORD: ${MAIL-PASSWORD}

